# Generated by Django 5.0 on 2023-12-29 00:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Book",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=45)),
                ("author", models.CharField(blank=True, max_length=45)),
                ("publication_year", models.PositiveIntegerField(default=0)),
                ("short_description", models.TextField(blank=True, max_length=180)),
                ("full_description", models.TextField(blank=True)),
                ("last_read_date", models.DateField(blank=True)),
                ("updated", models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
